language: cpp
sudo: required
os: linux 
dist: trusty
before_script:
  - curl http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.7 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install clang-3.7 lldb-3.7 -y
script:
  - mkdir build
  - cd build
  - cmake .. && make && make install
install:
   - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
compiler: clang