language: cpp
sudo: required
os: linux 
dist: trusty
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-5 -y
script:
  - mkdir build
  - cd build
  - cmake .. && make && make install
compiler: gcc-5