language: cpp
sudo: required
os: linux 
dist: trusty
compiler: gcc
cache: apt
before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gcc-5 g++-5 -y
script:
  - mkdir build
  - cd build
  - cmake .. && cmake --build .
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
