language: cpp
sudo: required
os: linux 
dist: trusty
cache: apt
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-5
   - cmake   
script:
  - mkdir build
  - cd build
  - cmake .. && make && make install
compiler: gcc-5