version: 1.0.{build}
os: Visual Studio 2015
platform:
  - x86
  - x64

matrix:
  fast_finish: true
  - environment:
    build_type: Debug
  - environment:
    build_type: Release

before_build:
  configuration: {build_type}
  cmd: cmake -DCMAKE_BUILD_TYPE={build_type} .
        
build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal