ersion: 1.0.{build}
os: Visual Studio 2015
platform:
  - x86
  - x64
matrix:
  # first group
  before_build:
    - configuration: Debug
    - cmd: cmake -DCMAKE_BUILD_TYPE=Debug .
  before_build:
    - configuration: Release
    - cmd: cmake -DCMAKE_BUILD_TYPE=Release .

matrix:
  fast_finish: true

build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal