version: 1.0.{build}
os: Visual Studio 2015
platform:
  - x86
  - x64
configuration:
  - Release  
matrix:
  fast_finish: true
before_build:
  cmd: cmake -DCMAKE_BUILD_TYPE=Release .
build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal