version: 1.0.{build}
os: Visual Studio 2015
platform:
  - x86
  - x64

environment:
  build_type: Debug
  build_type: Release
  
matrix:
  fast_finish: true

before_build:
  configuration: %build_type%
  cmd: cmake -DCMAKE_BUILD_TYPE=%build_type% .
        
build:
  project: ALL_BUILD.vcxproj
  parallel: true
  verbosity: minimal