option(BUILD_SHARED_LIBS "Build Shared libraries" OFF)
if(UNIX)
    option(CROSSBUILD "Build CrossPlatform libraries" OFF)
    if(CROSSBUILD)
        set(TOOLCHAIN "" CACHE STRING "Set the toolchain for cross builds" )
    endif(CROSSBUILD)
endif(UNIX)

option(BUILD_ALL "Build all modules" ON)
option(BUILD_OPENSSL "Build OpenSSL" ON)
option(BUILD_BOOST "Build Boost" ON)
option(BUILD_GTEST "Build GoogleTest" ON)